# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "proc_gen_game"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "plugins/*"
]

[dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.20.0"
bevy_cursor = "0.1.1"
bevy_pancam = "0.9.0"
test_plugin = { path = "plugins/test_plugin" }


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
